# Generated by Django 4.1.3 on 2022-11-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco2work_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='type',
        ),
        migrations.AddField(
            model_name='activity',
            name='vehicle',
            field=models.CharField(default='', max_length=100),
        ),
    ]
